## Testing ground for the kinematics/dynamics in python

In [3]:
import numpy as np

In [12]:
def get_RotX(angle): # 
    
    RX = np.array([[1, 0, 0], 
                   [0, np.cos(angle), -np.sin(angle)], 
                   [0, np.sin(angle), np.cos(angle)]])    
    return RX

def get_RotY(angle): 
    
    RY = np.array([[np.cos(angle), 0, np.sin(angle)], 
                   [0, 1, 0], 
                   [-np.sin(angle), 0, np.cos(angle)]])
    return RY
    
def get_RotZ(angle): 
    
    RZ = np.array([[np.cos(angle), -np.sin(angle), 0],
                   [np.sin(angle), np.cos(angle), 0], 
                   [ 0, 0, 1]] )
    return RZ

In [25]:
bRc = np.matmul(get_RotX(np.pi/2), get_RotY(np.pi/2))
cdt = np.array([-0.04, 0.00, 0.46]).reshape(3,1)

print(cdt.shape)
T_ = np.matrix(np.hstack((bRc, cdt)))
T_init = np.matrix(np.vstack((T_, np.array([0, 0, 0, 1])))).round(5)
print(T_init)

(3, 1)
[[ 0.    0.    1.   -0.04]
 [ 1.    0.   -0.    0.  ]
 [-0.    1.    0.    0.46]
 [ 0.    0.    0.    1.  ]]


In [24]:
p0 = np.array([1, 2, 3, 4]).reshape(4, 1)
p1 = np.array([2, 3, 4, 5]).reshape(4, 1) 

np.matmul(T_init, [p0, p1, -p0, -p1]).T

matrix([[ 2.84,  3.8 , -2.84, -3.8 ],
        [ 1.  ,  2.  , -1.  , -2.  ],
        [ 3.84,  5.3 , -3.84, -5.3 ],
        [ 4.  ,  5.  , -4.  , -5.  ]])

In [36]:
c_rw1 = np.array([-0.25, -0.2, 1.4]) # Calib point 
p_rw2 = np.array([-0.3, -0.3, 1.2]) # Measurement point
W
p_d = p_rw2 - c_rw1 
# This is correct transformation matrix [camera color frame --> human frame]
R = np.matrix([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
p_n = np.matmul(R, p_d)

In [37]:
print(p_n)

[[-0.2  -0.05 -0.1 ]]


In [31]:
R = np.matmul(get_RotX(np.pi/2), get_RotY(np.pi/2)).round(4).T

In [32]:
print(R)

[[ 0.  1. -0.]
 [ 0.  0.  1.]
 [ 1. -0.  0.]]


In [18]:
np.cos(np.pi)

-1.0